baseurl: https://r-lum.github.io/xlum_specification
languageCode: en-us
title: XLUM-specification
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
uglyurls: false
publishdir: "public/"
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: XLUM specification
      url: /specification/
      weight: 1
      pre: "<i class=\"bi bi-journal-text\"></i>"
    - name: Latest XSD-Schema
      url: /xsd-schema/
      weight: 1000
      pre: "<i class=\"bi bi bi-body-text\"></i>"
    - name: About
      url: /about/
      weight: 3000
      pre: "<i class=\"bi bi bi-question-square\"></i>"
    - name: GitHub
      url: https://github.com/R-Lum/xlum_specification
      weight: 9000
      pre: "<i class=\"bi bi-arrow-up-right-square\"></i>"
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 3.2.2
  description: Built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
    - xml
    - bash
    - sh
  highlightjsTheme: xcode
  highlightjsVersion: 11.5.1
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: true
    lineNos: true
    style: monokai
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
